name: "[CI] Lint / Lint code"
on:
  push:
    branches:
      - main
      - release/*
      - "*-stable"
  pull_request:

env:
  RUBY_VERSION: 3.2.6
  NODE_VERSION: 18.17.1
  DISABLE_SPRING: 1

jobs:
  lint-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set bundle local config configvendor/bundle path
        run: bundle config set --local path 'vendor/bundle'

      - name: Install Ruby deps
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bundle install --jobs 4 --retry 3

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec mdl *.md
        name: Lint Markdown files

      - run: bundle exec erblint app/**/*.erb
        name: Lint ERB files 

